version: '3.8'

services:

  nginx:
    container_name: ddd-starter-nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
      - php
    networks:
      - cnd_network

  php:
    container_name: ddd-starter-php
    user: '${USER_ID}:${GROUP_ID}'
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - cnd_network

  mailer:
    container_name: ddd-starter-mailer
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - cnd_network

  database:
    container_name: ddd-starter-database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      interval: 10s
      retries: 5
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - cnd_network

  redis:
    container_name: ddd-starter-redis
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
    networks:
      - cnd_network
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

networks:
  cnd_network:

volumes:
  database_data:
  redis_data:
